<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('Magento_Cms::default/home.phtml')->toHtml(); ?>

<script>
  var hostName = window.location.hostname.split(".");
  if (
    hostName[hostName.length - 1] === "ch" ||
    ["CH", undefined].includes(document.documentElement.lang.split("-")[1])
  ) {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.async = true;
    script.src = "https://api.sovendus.com/js/landing.js";
    document.body.appendChild(script);
  }
</script>