<?php

use Sovendus\SovendusApp\ViewModel\Order;
use Magento\Checkout\Block\Onepage\Success;
// /** @var $block Success */
// /** @var $viewModel Order */

$viewModel = $block->getData('view_model');
$viewModel->initializeSovendusData($block);
if ($viewModel->isActive) {
    echo <<<EOD
            <script>

            </script>
        EOD;
}
?>

<script type="text/javascript" src="<?php echo $block->getViewFileUrl('Sovendus_SovendusApp::js/thankyou-page.js'); ?>"></script>